recipes-zarhus: add alsa to separate packagegroups
zarhus/meta-zarhus pull request #20
Opened 2024-08-13 07:35 UTC by dancios

This patch adds packagegroups:
* zarhus-alsa
* zarhus-alsa-tools

2024-08-13 10:24 UTC, DaniilKl commented
@dancios, you should mark a PR as a draft if it is not ready for review.

2024-08-14 19:11 UTC, m-iwanicki requested changes

2024-08-14 19:11 UTC, m-iwanicki commented on recipes-zarhus/packagegroups/packagegroup-zarhus.bb
> +    ncurses \
You can

```suggestion
    ${PN}-alsa \
```

if alsa-tools depends on alsa

2024-08-14 19:11 UTC, m-iwanicki commented on recipes-zarhus/packagegroups/packagegroup-zarhus.bb
> +    alsa-utils \
Might be useful?

```suggestion
RDEPENDS:${PN}-alsa = " \
    packagegroup-base-alsa \
    alsa-utils \
```

Might need `alsa` in MACHINE_FEATURES if it isn't there. Or just copy https://git.yoctoproject.org/poky/plain/meta/recipes-core/packagegroups/packagegroup-base.bb and add

```
${@bb.utils.contains("MACHINE_FEATURES", "alsa", "packagegroup-zarhus-alsa", "", d)} \
${@bb.utils.contains("MACHINE_FEATURES", "alsa", "packagegroup-zarhus-alsa-tools", "", d)} \ 
```

to PACKAGES

2024-08-14 19:11 UTC, m-iwanicki commented on recipes-zarhus/packagegroups/packagegroup-zarhus.bb
> +    ncurses \
Or maybe the other way include alsa-tools in alsa (though I think alsa-tools depends on alsa seems more correct)

2024-08-14 19:11 UTC, m-iwanicki commented on recipes-zarhus/packagegroups/packagegroup-zarhus.bb
> +    ncurses \
Is this needed? Usually recipes that need this to run should have this in RDEPENDS in their own recipe.

2024-08-27 16:01 UTC, macpijan commented
Thanks for comments @m-iwanicki , I have done some very basic cleanup here and moved the rest into issue: https://github.com/zarhus/zarhus-issues/issues/28

2024-08-27 16:01 UTC, merged